#
# Recommended minimum configuration:
#
# acl localnet src 0.0.0.1-0.255.255.255
acl localnet src 10.0.0.0/8
# acl localnet src 100.64.0.0/10
# acl localnet src 169.254.0.0/16
# acl localnet src 172.16.0.0/12
# acl localnet src 192.168.0.0/16
# acl localnet src fc00::/7
# acl localnet src fe80::/10

acl SSL_ports port 443
# acl Safe_ports port 80
# acl Safe_ports port 21
acl Safe_ports port 443
# acl Safe_ports port 70
# acl Safe_ports port 210
# acl Safe_ports port 1025-65535
# acl Safe_ports port 280
# acl Safe_ports port 488
# acl Safe_ports port 591
# acl Safe_ports port 777

acl pkg_mirrors dstdomain pkg.omnios.org
acl pkg_mirrors dstdomain us-west.mirror.omnios.org
# acl pkg_mirrors dstdomain dl-cdn.alpinelinux.org

#
# Access rules
#
# http_access deny !Safe_ports
# http_access deny CONNECT !SSL_ports
# # http_access allow localhost manager
# http_access deny manager
# http_access deny to_localhost
# http_access deny to_linklocal

# allow localnet to reach pkg mirrors only
http_access allow CONNECT localnet pkg_mirrors
http_access allow localnet pkg_mirrors

http_access deny all

http_port 3128

visible_hostname mproxy

coredump_dir /var/opt/ooce/squid/cache

# refresh_pattern ^ftp:           1440    20%     10080
# refresh_pattern -i (/cgi-bin/|\?) 0     0%      0
