name: Lint Tests
permissions:
  contents: read
on: 
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: test-lint
  cancel-in-progress: true

jobs:
  typo-checks:
    name: Typo Checks
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # 6.0.2
        with:
          persist-credentials: false
      - name: Check for Typos
        uses: crate-ci/typos@78bc6fb2c0d734235d57a2d6b9de923cc325ebdd # 1.43.4
